### ISSUE TITLE
[bug] Unique index (Primary Key) is not working in the example.

### ISSUE THREAD

**Issue by uds5501** [tursodatabase/turso#530] opened 2024-12-21 07:54 UTC
Extending the example given in the readme, I attempted the following - 

```
Limbo v0.0.10
Enter ".help" for usage hints.
limbo> CREATE TABLE users (id INT PRIMARY KEY, username TEXT);
limbo> INSERT INTO users VALUES (1, 'alice');
limbo> INSERT INTO users VALUES (1, 'abra'); // should've failed.
limbo> select * from users;
1|alice
1|abra
```

This should've failed to insert (1, 'abra') due to unique constraint but it didn't.
Would be happy to pick the fix if it's indeed an error btw :)

**Comment by jussisaurio** [comment] 2024-12-21 12:58
Duplicate of https://github.com/tursodatabase/limbo/issues/472

**Closed by jussisaurio** 2024-12-21 12:58 UTC
Labels: compatibility
